
# Enable colors and change prompt:
autoload -U colors && colors
	
setopt PROMPT_SUBST  # Enable prompt theme substitution

autoload -Uz vcs_info
precmd() {
    vcs_info
}
setopt prompt_subst

# Set the format for displaying Git status (branch name inside parentheses)
zstyle ':vcs_info:git:*' formats '%F{blue} (%b)%f'

PS1='%B%F{cyan}%1~%f${vcs_info_msg_0_} %F{red}>%f%b '




#PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
# function zle-keymap-select {
#   if [[ ${KEYMAP} == vicmd ]] ||
#      [[ $1 = 'block' ]]; then
#     echo -ne '\e[1 q'
#   elif [[ ${KEYMAP} == main ]] ||
#        [[ ${KEYMAP} == viins ]] ||
#        [[ ${KEYMAP} = '' ]] ||
#        [[ $1 = 'beam' ]]; then
#     echo -ne '\e[5 q'
#   fi
# }
# zle -N zle-keymap-select
# zle-line-init() {
#     zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
#     echo -ne "\e[5 q"
# }
# zle -N zle-line-init
# echo -ne '\e[5 q' # Use beam shape cursor on startup.
# preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

# Use lf to switch directories and bind it to ctrl-o
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd\n'

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line


# Load zsh-syntax-highlighting; should be last.
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null


alias exa="exa -t=mod --time-style=default --sort=type --git"
alias ls='ls --color=auto -h --group-directories-first'
alias grep='grep --color=auto'



alias vi='nvim'
alias ll='exa -l'
alias la='exa -la'
alias yay='yay --color=auto'

alias i='doas pacman -S'
alias u='doas pacman -Syu'
alias q='doas pacman -Ss'
alias r='doas pacman -Rns'

# alias tree='tree -C --du -h'
alias tree='exa -T'
alias cat='bat'
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkd="mkdir -pv"
alias diff="diff --color=auto"
alias nmcli="nmcli --color=auto"
alias kf="ps aux | fzy | awk '{print $2}' | xargs kill"
alias vf='vi $(find . -type f | fzy)'



print -n '\e[2 q'
